kind: pipeline
type: docker
name: deploy

steps:
  - name: Tailwind build
    image: node:17-alpine
    commands:
      - npm install
      - npm run style-build
  - name: Zola check
    image: registry.berrio.dev/zola
    commands:
      - zola check

image_pull_secrets:
  - dockerconfig
