# The URL the site will be built for
base_url = "https://karatewadounims.de"

title = "Karate Wado Uni Münster"
description = ""

default_language = "de"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
author = "Miguel Berrio"
